version: 2

builds:
  - main: ./main.go
    binary: a9s
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
